# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]  # Match this with your server's Node.js version

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm ci
      - name: Set up environment
        run: |
          touch .env
          echo "${{secrets.EWORLD_ENV_FILE}}" > .env
      - name: Stop all PM2 processes
        run: pm2 stop all || true
      - name: Start E-World process
        run: pm2 start server.js --name E-World
      - name: Verify server is running
        run: |
          sleep 10 # Give some time for the server to start
          curl -I http://localhost:3000/health || exit 1



